---
title: "DATA608 - Story 6"
author: "Glen Dale Davis"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, warning = FALSE, message = FALSE}
library(tidyverse)
library(snakecase)
library(RColorBrewer)
library(ggpubr)
library(nnet)
library(fpp3)
library(statebins)
library(cowplot)
library(ggflowchart)
library(igraph)

```

```{r theme}
cur_theme <- theme_set(theme_classic())
palette <- brewer.pal(n = 12, name = "Paired")
greys <- brewer.pal(n = 9, name = "Greys")
set.seed(1006)

```

```{r food_security_data}
food_sec_var_names <- c("Summary Food Security Status",
                        "Detailed Food Security Status",
                        "Food Security Raw Score",
                        "Food Security Rasch Scale Score",
                        "Children's Food Security Status",
                        "Children's Food Security Raw Score",
                        "Children's Food Security Rasch Scale Score",
                        "Adult Food Security Status",
                        "Adult Food Security Raw Score",
                        "Adult Food Security Rasch Scale")
food_sec_var_codes_12mon <- c("HRFS12M1", "HRFS12MD", "HRFS12M3", "HRFS12M4",
                              "HRFS12MC", "HRFS12M6", "HRFS12M7", "HRFS12M8",
                              "HRFS12M9", "HRFS12ME")
food_sec_var_codes_30d <- c("HRFS30D1", "HRFS30D2", "HRFS30D3", "HRFS30D4",
                            "HRFS30D5", "HRFS30D6", "HRFS30D7", "HRFS30D8",
                            "HRFS30D9", "HRFS30DE")
personal_var_names <- c("Recode for HEFAMINC", "FAMILY INCOME", "SEX",
                        "PERSONS AGE", "HOUSEHOLD TYPE", "HOUSEHOLD MEMBERS",
                        "HOUSEHOLD IDENTIFIER", "LIVING QUARTERS",
                        "TYPE OF HOUSING UNIT",
                        "HIGHEST LEVEL OF SCHOOL COMPLETED OR DEGREE RECEIVED",
                        "RACE")
personal_var_codes <- c("HRPOOR", "HEFAMINC", "PESEX", "PRTAGE", "HRHTYPE",
                        "HRNUMHOU", "HRHHID", "HETENURE", "HEHOUSUT",
                        "PEEDUCA", "PTDTRACE")
geographic_var_names <- c("REGION", "DIVISION", "FIPS STATE CODE")
geographic_var_codes <- c("GEREG", "GEDIV", "GESTFIPS")
all_var_codes <- c(food_sec_var_codes_12mon, food_sec_var_codes_30d,
                   personal_var_codes, geographic_var_codes)
base_url <- "https://raw.githubusercontent.com/geedoubledee/data608_story6/main/data/dec22pub_"

fnames <- c("pt_1.csv", "pt_2.csv", "pt_3.csv", "pt_4.csv", "pt_5.csv",
            "pt_6.csv", "pt_7.csv", "pt_8.csv", "pt_9.csv")
food_insecurity_df <- as.data.frame(matrix(nrow = 0,
                                           ncol = length(all_var_codes)))
colnames(food_insecurity_df) <- all_var_codes
df_list <- as.list(rep(0, length(fnames)))
for (i in 1:length(fnames)){
    df_part <- read.csv(paste0(base_url, fnames[i]))
    df_part <- df_part |>
        select(all_of(all_var_codes))
    df_list[[i]] <- df_part
}
food_insecurity_df <- food_insecurity_df |>
    bind_rows(df_list)

```

```{r food_security_mutations}
food_insecurity_df <- food_insecurity_df |>
    mutate(HEFAMINC = case_when(HEFAMINC < 0 ~ NA,
                                HEFAMINC < 2 ~ 0,
                                HEFAMINC < 3 ~ 5000,
                                HEFAMINC < 4 ~ 7500,
                                HEFAMINC < 5 ~ 10000,
                                HEFAMINC < 6 ~ 12500,
                                HEFAMINC < 7 ~ 15000,
                                HEFAMINC < 8 ~ 20000,
                                HEFAMINC < 9 ~ 25000,
                                HEFAMINC < 10 ~ 30000,
                                HEFAMINC < 11 ~ 35000,
                                HEFAMINC < 12 ~ 40000,
                                HEFAMINC < 13 ~ 50000,
                                HEFAMINC < 14 ~ 60000,
                                HEFAMINC < 15 ~ 75000,
                                HEFAMINC < 16 ~ 100000,
                                TRUE ~ 150000),
           HRPOOR = factor(case_when(HRPOOR < 2 ~ "Below",
                                     TRUE ~ "Above"),
                           levels = c("Above", "Below")),
           HRFS12MD = factor(case_when(HRFS12MD < 0 ~ NA,
                                       HRFS12MD < 3 ~ "High or Marginal",
                                       HRFS12MD < 4 ~ "Low",
                                       TRUE ~ "Very Low"),
                             levels = c("High or Marginal", "Low", "Very Low"),
                             exclude = NULL),
           HRFS12MC = factor(case_when(HRFS12MC < 0 ~ NA,
                                       HRFS12MC < 2 ~ "High or Marginal",
                                       HRFS12MC < 3 ~ "Low",
                                       TRUE ~ "Very Low"),
                             levels = c("High or Marginal", "Low", "Very Low"),
                             exclude = NULL),
           HRFS12M8 = factor(case_when(HRFS12M8 < 0 ~ NA,
                                       HRFS12M8 < 3 ~ "High or Marginal",
                                       HRFS12M8 < 4 ~ "Low",
                                       TRUE ~ "Very Low"),
                             levels = c("High or Marginal", "Low", "Very Low"),
                             exclude = NULL),
           HRFS30D2 = factor(case_when(HRFS30D2 < 0 ~ NA,
                                       HRFS30D2 < 3 ~ "High or Marginal",
                                       HRFS30D2 < 4 ~ "Low",
                                       TRUE ~ "Very Low"),
                             levels = c("High or Marginal", "Low", "Very Low"),
                             exclude = NULL),
           HRFS30D5 = factor(case_when(HRFS30D5 < 0 ~ NA,
                                       HRFS30D5 < 2 ~ "High or Marginal",
                                       HRFS30D5 < 3 ~ "Low",
                                       TRUE ~ "Very Low"),
                             levels = c("High or Marginal", "Low", "Very Low"),
                             exclude = NULL),
           HRFS30D8 = factor(case_when(HRFS30D8 < 0 ~ NA,
                                       HRFS30D8 < 3 ~ "High or Marginal",
                                       HRFS30D8 < 4 ~ "Low",
                                       TRUE ~ "Very Low"),
                             levels = c("High or Marginal", "Low", "Very Low"),
                             exclude = NULL),
           PESEX = factor(case_when(PESEX < 0 ~ NA,
                                    PESEX < 2 ~ "Male",
                                    TRUE ~ "Female"),
                          levels = c("Male", "Female"),
                          exclude = NULL),
           HETENURE = factor(case_when(HETENURE < 0 ~ NA,
                                       HETENURE < 2 ~ "Owned",
                                       HETENURE < 3 ~ "Rented",
                                       TRUE ~ "Occupied"),
                             levels = c("Owned", "Rented", "Occupied"),
                             exclude = NULL),
           HEHOUSUT = factor(case_when(HEHOUSUT < 0 ~ NA,
                                       HEHOUSUT < 2 ~ "House/Apt",
                                       HEHOUSUT < 4 ~ "Hotel/Motel",
                                       HEHOUSUT < 5 ~ "Rooming/Boarding House",
                                       HEHOUSUT < 7 ~ "Mobile Home",
                                       HEHOUSUT < 8 ~ NA,
                                       HEHOUSUT < 9 ~ "Rooming/Boarding House",
                                       HEHOUSUT < 10 ~ "Hotel/Motel",
                                       HEHOUSUT < 11 ~ "Tent/Trailer Site",
                                       HEHOUSUT < 12 ~ "Student Dorm",
                                       TRUE ~ NA),
                             levels = c("House/Apt", "Hotel/Motel",
                                        "Rooming/Boarding House",
                                        "Mobile Home", "Tent/Trailer Site",
                                        "Student Dorm"),
                             exclude = NULL),
           PEEDUCA = factor(case_when(PEEDUCA < 0 ~ NA,
                                      PEEDUCA < 34 ~ "Elementary",
                                      PEEDUCA < 35 ~ "Junior High",
                                      PEEDUCA < 39 ~ "High School",
                                      PEEDUCA < 40 ~ "High School Diploma",
                                      PEEDUCA < 41 ~ "College",
                                      PEEDUCA < 43 ~ "Associate's Degree",
                                      PEEDUCA < 44 ~ "Bachelor's Degree",
                                      PEEDUCA < 45 ~ "Master's Degree",
                                      PEEDUCA < 46 ~ "Professional Degree",
                                      TRUE ~ "Doctorate Degree"),
                            levels = c("Elementary", "Junior High", "High School",
                                       "High School Diploma", "College",
                                       "Associate's Degree", "Bachelor's Degree",
                                       "Master's Degree", "Professional Degree",
                                       "Doctorate Degree"),
                            exclude = NULL),
           PTDTRACE = factor(case_when(PTDTRACE < 0 ~ NA,
                                       PTDTRACE < 2 ~ "White",
                                       PTDTRACE < 3 ~ "Black",
                                       PTDTRACE < 4 ~ "American Indian/Alaskan Native",
                                       PTDTRACE < 5 ~ "Asian",
                                       PTDTRACE < 6 ~ "Hawaiian/Pacific Islander",
                                       TRUE ~ "Mixed"),
                             levels = c("White", "Black",
                                        "American Indian/Alaskan Native",
                                        "Asian", "Hawaiian/Pacific Islander",
                                        "Mixed"),
                             exclude = NULL),
           GEREG = factor(case_when(GEREG < 2 ~ "Northeast",
                                    GEREG < 3 ~ "Midwest",
                                    GEREG < 4 ~ "South",
                                    GEREG < 5 ~ "West")),
           GEDIV = factor(case_when(GEDIV < 2 ~ "New England",
                                    GEDIV < 3 ~ "Middle Atlantic",
                                    GEDIV < 4 ~ "East North Central",
                                    GEDIV < 5 ~ "West North Central",
                                    GEDIV < 6 ~ "South Atlantic",
                                    GEDIV < 7 ~ "East South Central",
                                    GEDIV < 8 ~ "West South Central",
                                    GEDIV < 9 ~ "Mountain",
                                    TRUE ~ "Pacific")),
           GESTFIPS = factor(case_when(GESTFIPS < 2 ~ "AL",
                                       GESTFIPS < 3 ~ "AK",
                                       GESTFIPS < 5 ~ "AZ",
                                       GESTFIPS < 6 ~ "AR",
                                       GESTFIPS < 7 ~ "CA",
                                       GESTFIPS < 9 ~ "CO",
                                       GESTFIPS < 10 ~ "CT",
                                       GESTFIPS < 11 ~ "DE",
                                       GESTFIPS < 12 ~ "DC",
                                       GESTFIPS < 13 ~ "FL",
                                       GESTFIPS < 14 ~ "GA",
                                       GESTFIPS < 16 ~ "HI",
                                       GESTFIPS < 17 ~ "ID",
                                       GESTFIPS < 18 ~ "IL",
                                       GESTFIPS < 19 ~ "IN",
                                       GESTFIPS < 20 ~ "IA",
                                       GESTFIPS < 21 ~ "KS",
                                       GESTFIPS < 22 ~ "KY",
                                       GESTFIPS < 23 ~ "LA",
                                       GESTFIPS < 24 ~ "ME",
                                       GESTFIPS < 25 ~ "MD",
                                       GESTFIPS < 26 ~ "MA",
                                       GESTFIPS < 27 ~ "MI",
                                       GESTFIPS < 28 ~ "MN",
                                       GESTFIPS < 29 ~ "MS",
                                       GESTFIPS < 30 ~ "MO",
                                       GESTFIPS < 37 ~ "NY",
                                       GESTFIPS < 38 ~ "NC",
                                       GESTFIPS < 39 ~ "ND",
                                       GESTFIPS < 40 ~ "OH",
                                       GESTFIPS < 41 ~ "OK",
                                       GESTFIPS < 42 ~ "OR",
                                       GESTFIPS < 44 ~ "PA",
                                       GESTFIPS < 45 ~ "RI",
                                       GESTFIPS < 46 ~ "SC",
                                       GESTFIPS < 47 ~ "SD",
                                       GESTFIPS < 48 ~ "TN",
                                       GESTFIPS < 49 ~ "TX",
                                       GESTFIPS < 50 ~ "UT",
                                       GESTFIPS < 51 ~ "VT",
                                       GESTFIPS < 53 ~ "VA",
                                       GESTFIPS < 54 ~ "WA",
                                       GESTFIPS < 55 ~ "WV",
                                       GESTFIPS < 56 ~ "WI",
                                       TRUE ~ "WY")))
           
           

```

```{r nutrition_data}
my_url <- "https://raw.githubusercontent.com/geedoubledee/data608_story6/main/data/suite-of-food-security-indicators_usa.csv"
nutrition_df <- read.csv(my_url, )
nutrition_df <- nutrition_df[-1, ]
colnames(nutrition_df) <- to_snake_case(colnames(nutrition_df))
nutrition_df$year <- as.integer(nutrition_df$year)

```

```{r visualizations1}
children_item_codes <- rev(c("21026", "210260", "21025", "210250", "21041",
                         "210410", "21049", "210490"))
nutrition_df <- nutrition_df |>
    filter(item_code %in% children_item_codes)
labels <- rev(c("Wasting", "Wasting", "Stunted", "Stunted", "Overweight", "Overweight",
                "Low Birthweight", "Low Birthweight"))
names(labels) <- children_item_codes
nutrition_df <- nutrition_df |>
    mutate(label = str_replace_all(item_code, pattern = labels))
title <- "Wasting Is the Only Malnutrition Condition on Decline in the United States"
caption <- "Source: https://data.humdata.org/dataset/faostat-food-security-indicators-for-united-states-of-america"
fill_palette <- palette[c(1, 3, 9, 5)]
color_palette <- palette[c(1, 3, 9, 5)]
keep <- c("year", "label", "value")
nutrition_ts <- nutrition_df |>
    filter(unit == "%") |>
    select(all_of(keep)) |>
    as_tsibble(index = year, key = label) |>
    fill_gaps(.full = TRUE) |>
    fill(value, .direction = "down")
title_str <- "Many US Children Under 5 Experience Conditions of Malnutrition, and\nMost Conditions Are Slightly More Prevalant Today than 20 Years Ago"
cap_str <- "Source: https://data.humdata.org/dataset/faostat-food-security-indicators-for-united-states-of-america"
nutrition_plot_df <- nutrition_ts |>
    as_tibble() |>
    filter(year %in% c(2002, 2022)) |>
    group_by(label) |>
    arrange(year) |>
    mutate(value = as.numeric(value),
           diff = ifelse(year == 2022, paste0(format(
                        diff(value - lag(value, default = first(value))),
                        nsmall = 1), "%"), NA)) |>
    ungroup() |>
    mutate(lab = ifelse(str_detect(diff, "-"), diff, paste0("+", diff)))
p1 <- nutrition_plot_df |>
    ggplot(aes(x = label, y = value, group = label, color = label, fill = label)) +
    geom_col() +
    geom_text(aes(label = lab), vjust = -0.75,
              size = 4, fontface = "bold") +
    scale_y_continuous(limits = c(0, 9), breaks = seq(0, 8, 1)) +
    scale_color_manual(values = color_palette) +
    scale_fill_manual(values = fill_palette) +
    facet_grid(~ year, scales = "free_x", space = "free_x", switch = "y") +
    labs(x = "Condition", y = "Percentage Affected",
         title = title_str,
         caption = cap_str) +
    theme(legend.position = "none", panel.spacing = unit(0, units = "cm"),
          strip.placement = "outside",
          strip.background = element_blank(),
          strip.text = element_text(size = 12, face = "bold"),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.caption.position = "plot",
          plot.title.position = "plot",
          plot.caption = element_text(hjust = 0))
p1

```

```{r visualizations3}
model1 <- multinom(HRFS12MD ~ HEFAMINC,
                   data = food_insecurity_df |>
                       filter(!is.na(HEFAMINC) & !is.na(HRFS12MD)))
model1
income_levels <- seq(0, 150000, 1000)
predictions <- data.frame(HEFAMINC = income_levels,
                          predict(model1, data.frame(HEFAMINC = income_levels),
                                  type = "probs"))
lpred <- gather(predictions, HRFS12MD, probability, -HEFAMINC)
levs <- c("High or Marginal", "Very Low")
names(levs) <- c("High.or.Marginal", "Very.Low")
lpred <- lpred |>
    mutate(HRFS12MD = str_replace_all(HRFS12MD, pattern = levs)) |>
    filter(HRFS12MD != "High or Marginal")
color_palette <- palette[7:8]
breaks = seq(0, 100000, 25000)
lpred_breaks = lpred[lpred$HEFAMINC %in% breaks, ]
annotations <- data.frame(x = rep(breaks, 2),
                          HRFS12MD = lpred_breaks$HRFS12MD,
                          y = round(lpred_breaks$probability * 100, 1))
annotations <- annotations |>
    mutate(lab = paste0(format(y, nsmall = 1), "%"))
title_str <- "The Probability of Experiencing Low or Very Low Food Security Decreases\nSignificantly as Family Income Increases"
cap_str <- "Source: https://www.census.gov/data/datasets/time-series/demo/cps/cps-supp_cps-repwgt/cps-food-security.html"
first <- lpred |>
    filter(HEFAMINC == 0)
p3 <- lpred |>
    ggplot(aes(x = HEFAMINC, y = round(probability * 100, 1), group = HRFS12MD,
               color = HRFS12MD)) +
    geom_line() +
    geom_text(data = first, aes(x = HEFAMINC - 18000, y = round(probability * 100, 1),
                               label = HRFS12MD, color = HRFS12MD)) + 
    scale_x_continuous(limits = c(-20000, 150000), breaks = seq(0, 150000, 25000)) +
    scale_y_continuous(limits = c(0, 25), breaks = seq(0, 25, 5),
                       position = "right") +
    geom_label(data = annotations, aes(x = x, y = y, label = lab, fill = HRFS12MD),
                                       color = "white", fontface = "bold") +
    scale_color_manual(values = color_palette,
                       guide = guide_legend(reverse = TRUE)) +
    scale_fill_manual(values = color_palette,
                       guide = guide_legend(reverse = TRUE)) +
    labs(y = "Probability (%)",
         x = "Family Income (USD)",
         title = title_str,
         caption = cap_str) + 
    theme(legend.position = "none",
          plot.caption = element_text(hjust = 0))
p3 

```

```{r visualizations4, warning = FALSE, message = FALSE}
keep <- c("HRPOOR")
pivot_cols <- c("HRFS12MD", "HRFS12MC", "HRFS12M8", "HRFS30D2", "HRFS30D5",
                "HRFS30D8")
pivot_df <- food_insecurity_df |>
    select(all_of(c(keep, pivot_cols))) |>
    pivot_longer(cols = pivot_cols, names_to = "Variable",
                 values_to = "Values") |>
    group_by(HRPOOR, Variable, Values) |>
    summarize(Freq = n()) |>
    filter(!is.na(Values)) |>
    group_by(HRPOOR, Variable) |>
    mutate(Total = sum(Freq)) |>
    ungroup() |>
    mutate(Perc = round(Freq / Total * 100, 1),
           Label = ifelse(Perc > 5, Perc, NA))
twelvemon <- c("HRFS12MC", "HRFS12M8")
var_labs <- c("Children", "Adults")
names(var_labs) <- twelvemon
fill_palette <- c(greys[4], palette[c(7, 8)])
title_str <- "Adults and Children in Families Whose Income Is Below 185% Poverty*\nExperience Low or Very Low Food Security at Much Higher Rates"
cap_str <- "*This percentage multiple of the poverty guidelines, which vary by family size and state, is used by\nfederal agencies to determine eligibility for public programs such as food assistance."
p4 <- pivot_df |>
    filter(Variable %in% twelvemon) |>
    ggplot(aes(x = HRPOOR, y = Perc, group = Values, color = Values, fill = Values)) +
    geom_col(position = "stack", lwd = 1.5, color = "white") +
    geom_text(aes(label = ifelse(!is.na(Label),
                                 paste0(sprintf("%1.0f", Label), "%"), NA)),
              position = position_stack(vjust = 0.5),
              size = 5, color = "white", fontface = "bold") +
    scale_fill_manual(values = fill_palette, guide = guide_legend(reverse = TRUE)) +
    scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 10)) +
    theme(legend.position = "top",
          legend.title = element_blank(),
          plot.caption = element_text(hjust = 0)) + 
    facet_grid(vars(Variable), labeller = labeller(Variable = var_labs)) +
    labs(y = "Percentage Affected",
         x = "185% Poverty",
         title = title_str,
         caption = cap_str) + 
    coord_flip()
p4

```

```{r visualizations2, warning = FALSE, message = FALSE}
#by state
keep <- c("GESTFIPS", "HRFS12MD")
pivot_cols <- c("HRFS12MD")
state_pivot_df <- food_insecurity_df |>
    select(all_of(c(keep))) |>
    pivot_longer(cols = pivot_cols, names_to = "Variable",
                 values_to = "Values") |>
    group_by(GESTFIPS, Variable, Values) |>
    summarize(Freq = n()) |>
    filter(!is.na(Values)) |>
    group_by(GESTFIPS, Variable) |>
    mutate(Total = sum(Freq)) |>
    ungroup() |>
    mutate(Perc = round(Freq / Total * 100, 1))
state_pivot_df_low_very_low_only <- state_pivot_df |>
    filter(Values != "High or Marginal") |>
    group_by(GESTFIPS) |>
    summarize(Total_Perc = sum(Perc))
zero <- as.data.frame(state.abb) |>
    filter(!state.abb %in% state_pivot_df_low_very_low_only$GESTFIPS)
zero <- zero |>
    mutate(GESTFIPS = state.abb,
           Total_Perc = 0) |>
    select(-state.abb)
state_pivot_df_low_very_low_only <- state_pivot_df_low_very_low_only |>
    bind_rows(zero) |>
    mutate(Bin = as.factor(case_when(Total_Perc == 0 ~ 0,
                                     Total_Perc < 5 ~ 5,
                                     Total_Perc < 10 ~ 10,
                                     Total_Perc < 15 ~ 15,
                                     TRUE ~ 20)))

title_str <- "States in the South Report the Highest Levels of Low or Very Low\nFood Security, but Very Few States Report <5%"
p2 <- state_pivot_df_low_very_low_only |>
    mutate(GESTFIPS = as.character(GESTFIPS)) |>
    statebins(state_col = "GESTFIPS", value_col = "Bin",
              ggplot2_scale_function = scale_fill_brewer,
              round = TRUE,
              palette = "Oranges") +
    theme_statebins(legend_position = "right") +
    labs(fill = "Percentage Affected")
title <- ggdraw() + 
    draw_label(title_str)
p2 <- plot_grid(title, p2, ncol = 1, rel_heights = c(0.1, 1))
p2

```

```{r visualizations5}
#by gender
keep <- c("PESEX")
pivot_cols <- c("HRFS12MD")
gender_pivot_df <- food_insecurity_df |>
    select(all_of(c(keep, pivot_cols))) |>
    pivot_longer(cols = pivot_cols, names_to = "Variable",
                 values_to = "Values") |>
    group_by(PESEX, Variable, Values) |>
    summarize(Freq = n()) |>
    filter(!is.na(Values)) |>
    group_by(PESEX, Variable) |>
    mutate(Total = sum(Freq)) |>
    ungroup() |>
    mutate(Perc = round(Freq / Total * 100, 1)) |>
    filter(Values != "High or Marginal")
color_palette <- palette[c(7, 8)]
fill_palette <- palette[c(7, 8)]
title_str <- "Female Respondents Report Their Families Experience Low or Very Low\nFood Security at Slightly Higher Rates than Male Respondents"
cap_str <- "Source: https://www.census.gov/data/datasets/time-series/demo/cps/cps-supp_cps-repwgt/cps-food-security.html"
p5 <- gender_pivot_df |>
    ggplot(aes(x = Values, y = Perc, group = Values, color = Values, fill = Values)) +
    geom_col() +
    geom_text(aes(label = paste0(format(Perc, nsmall = 1), "%")), vjust = -0.75,
              size = 4, fontface = "bold") +
    facet_grid(~ PESEX, scales = "free_x", space = "free_x", switch = "y") +
    scale_color_manual(values = color_palette) +
    scale_fill_manual(values = fill_palette) +
    scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, 1)) +
    theme(legend.position = "none", panel.spacing = unit(0, units = "cm"),
          strip.placement = "outside",
          strip.background = element_blank(),
          strip.text = element_text(size = 12, face = "bold"),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.caption.position = "plot",
          plot.title.position = "plot",
          plot.caption = element_text(hjust = 0)) +
    labs(y = "Percentage Affected",
         x = "Food Security",
         title = title_str,
         caption = cap_str)
p5

```

```{r visualizations6}
#childhood benefits and adulthood food security link
categories <- c("Neither SNAP nor WIC", "WIC Alone", "SNAP Alone",
                "Both SNAP and WIC")
outcome1 <- as.data.frame(c(rep("More Secure", 12), rep("Less Secure/No Change", 88)))
elements <- sample(nrow(outcome1))
outcome1 <- outcome1[elements, ]
outcome2 <- as.data.frame(c(rep("More Secure", 20), rep("Less Secure/No Change", 80)))
elements <- sample(nrow(outcome2))
outcome2 <- outcome2[elements, ]
outcome3 <- as.data.frame(c(rep("More Secure", 29), rep("Less Secure/No Change", 71)))
elements <- sample(nrow(outcome3))
outcome3 <- outcome3[elements, ]
outcome4 <- as.data.frame(c(rep("More Secure", 34), rep("Less Secure/No Change", 66)))
elements <- sample(nrow(outcome4))
outcome4 <- outcome4[elements, ]
outcomes <- outcome1 |>
    bind_cols(outcome2, outcome3, outcome4,
              expand.grid(seq_len(10), seq_len(10)))
colnames(outcomes) <- c(categories, "x", "y")
outcomes_pivot <- outcomes |>
    pivot_longer(cols = categories, names_to = "Category", values_to = "Outcome") |>
    mutate(Category = factor(Category, levels = categories),
           Outcome = as.factor(Outcome))
fill_palette <- palette[1:2]
title_str <- "Childhood Participation in SNAP and WIC Programs Improves Probability of\nBeing More Food Secure in Adulthood"
cap_str <- "SNAP stands for the Supplemental Nutrition Assistance Program\nWIC stands for the Special Supplemental Nutrition Program for Women, Infants, and Children\nSource: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9480484/"
p6 <- outcomes_pivot |>
    ggplot() +
    geom_tile(aes(x = x, y = y,
                  fill = Outcome), col = "white", size = 0.6) +
    facet_wrap(~ Category, nrow = 1) +
    scale_y_continuous(expand = c(0, 0)) +
    scale_x_continuous(expand = c(0, 0)) +
    coord_fixed() +
    labs(title = title_str,
         caption = cap_str) +
    scale_fill_manual(values = fill_palette) +
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          axis.title = element_blank(),
          axis.line = element_blank(),
          plot.caption = element_text(hjust = 0))
p6


```

```{r visualizations7}
#by age
model2 <- multinom(HRFS12MD ~ PRTAGE,
                   data = food_insecurity_df |>
                       filter(PRTAGE >= 0 & !is.na(HRFS12MD)))
model2
age_levels <- seq(0, 85, 1)
predictions2 <- data.frame(PRTAGE = age_levels,
                          predict(model2, data.frame(PRTAGE = age_levels),
                                  type = "probs"))
lpred2 <- gather(predictions2, HRFS12MD, probability, -PRTAGE)
levs <- c("High or Marginal", "Very Low")
names(levs) <- c("High.or.Marginal", "Very.Low")
lpred2 <- lpred2 |>
    mutate(HRFS12MD = str_replace_all(HRFS12MD, pattern = levs)) |>
    filter(HRFS12MD != "High or Marginal")
color_palette <- palette[7:8]
breaks2 = seq(25, 75, 10)
lpred2_breaks = lpred2[lpred2$PRTAGE %in% breaks2, ]
annotations2 <- data.frame(x = rep(breaks2, 2),
                          HRFS12MD = lpred2_breaks$HRFS12MD,
                          y = round(lpred2_breaks$probability * 100, 1))
annotations2 <- annotations2 |>
    mutate(lab = paste0(format(y, nsmall = 1), "%"))
title_str <- "Probability of Experiencing Low or Very Low Levels of Food Security\nDecreases as Age of Respondent Increases"
cap_str <- "Source: https://www.census.gov/data/datasets/time-series/demo/cps/cps-supp_cps-repwgt/cps-food-security.html"
first2 <- lpred2 |>
    filter(PRTAGE == 25)
p7 <- lpred2 |>
    filter(PRTAGE >= 25) |>
    ggplot(aes(x = PRTAGE, y = round(probability * 100, 1), group = HRFS12MD,
               color = HRFS12MD)) +
    geom_line() +
    geom_text(data = first2, aes(x = PRTAGE - 7, y = round(probability * 100, 1),
                               label = HRFS12MD, color = HRFS12MD)) + 
    scale_x_continuous(limits = c(15, 85), breaks = seq(25, 85, 5)) +
    scale_y_continuous(limits = c(0, 15), breaks = seq(0, 15, 5),
                       position = "right") +
    geom_label(data = annotations2, aes(x = x, y = y, label = lab, fill = HRFS12MD),
                                       color = "white", fontface = "bold") +
    scale_color_manual(values = color_palette,
                       guide = guide_legend(reverse = TRUE)) +
    scale_fill_manual(values = color_palette,
                       guide = guide_legend(reverse = TRUE)) +
    labs(y = "Probability (%)",
         x = "Age",
         title = title_str,
         caption = cap_str) + 
    theme(legend.position = "none",
          plot.caption = element_text(hjust = 0))
p7 

```

```{r visualizations8}
#malnutrition longterm effects
title_str <- "Malnutrition Conditions in Childhood Can Lead to Low Ability to Work\nand Low Quality of Life in the Longterm"
cap_str <- "Source: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3137999/"
flow_data <- tibble(
    from  = c("Poverty/Disease", "Inadequate Food\nConsumption",
              "Poor Diet/\nPhysical Inactivity", "Underweight/Stunting",
              "Short Stature/Obesity/\nHypertension/Diabetes",
              "Increased Fat Gain"),
    to = c("Underweight/Stunting", "Underweight/Stunting",
           "Increased Fat Gain",
           "Short Stature/Obesity/\nHypertension/Diabetes",
           "Low Ability to Work/\nLow Quality of Life",
           "Short Stature/Obesity/\nHypertension/Diabetes")
)
p8 <- ggflowchart(data = flow_data, text_size = 3.2, fill = "#FB9A99",
                  color = "#E31A1C", text_color = "black",
                  arrow_color = "#E31A1C") +
    labs(title = title_str,
         caption = cap_str) +
    theme(plot.caption = element_text(hjust = 0))
p8

```

